language: node_js

node_js:
  - '0.10'

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g bower
  - time bower install
  - time npm install

before_script:
  - npm install -g grunt-cli

script:
  - time grunt prod
