language: node_js

node_js:
  - '0.10'

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - npm install -g bower grunt-cli
  - time ./build/scripts/travis-install.bash

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - time grunt prod
